# Generated by Django 4.1 on 2024-11-11 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, null=True, unique=True)),
                ('location', models.JSONField(null=True)),
                ('current', models.JSONField(null=True)),
            ],
        ),
    ]
