# Generated by Django 4.1 on 2024-11-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_weatherupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
